name: Deploy to GCR

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: flatland-api
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          export_default_credentials: true
      - name: Build docker file
        run: gcloud builds submit --tag gcr.io/flatland-api/abbot-api
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/flatland-api/abbot-api
          service: abbot-api
          project: flatland-api
          region: us-central1
          service key: ${{ secrets.GCP_SERVICE_KEY }}
